### ISSUE TITLE
Object not found?

### ISSUE THREAD

**Issue by morrislaptop** [antalaron/action-splitsh#1]
`object not found - no match for id (bd235c10b45ebb3ba65e053b0f7a86e9bdd2f2d5)`

Any ideas?

**Comment by antalaron** [comment]
Basically that's beacuse the checkout actions's default behavior is that it has 1 commit depth.

Please, try with the following parameter in the checkout action:

```yaml
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
```
